version: 1.0.{build}
image: Visual Studio 2017

skip_branch_with_pr: true
skip_tags: true
pull_requests:
  do_not_increment_build_number: true

artifacts:
  - path: .build
  - path: .nugets\*.nupkg

for:

-
  branches:
    only:
      - master

  build_script:
    - cmd: build.cmd release