version: 1.0.{build}
image: Visual Studio 2017

skip_branch_with_pr: true
skip_tags: true
pull_requests:
  do_not_increment_build_number: true

artifacts:
  - path: .build
  - path: .nugets\*.nupkg

for:

-
  branches:
    only:
      - master

  build_script:
    - cmd: build.cmd release

  deploy:
    - provider: Environment
      name: NuGet public feed
      artifact: .nugets\*.nupkg

    - provider: GitHub    
      release: $(PackageVersion)
      description: 'Release v$(PackageVersion)'
      auth_token:
        secure: 2ijF4OfPYfIUTunubL/Z04ogADL9sx/gKW1jMRNJnAa1OpHZpSvCKmP0gvNs8C7h
      artifact: .nugets\*.nupkg, .build\build.zip